services:
  - type: web
    name: monofied
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_ENV
        value: production
